/**
 * Emits supabase/seed.sql from packages/shared.
 *
 * The challenge files are the single source of truth for challenge content.
 * Editing a challenge and running `pnpm seed` is the whole workflow — the
 * generated SQL is never hand-edited.
 *
 *   pnpm seed
 *
 * A note on the split between `challenges` and `challenge_grading`: the public
 * suite goes in the readable table so the challenge panel can show it, and the
 * full suite — public plus hidden — goes in the service-role-only table. The
 * hidden tests are marked in the test code itself (`{ hidden: true }` in JS,
 * `@hidden_test` in Python), never by position, so a challenge author cannot
 * accidentally award the 50-point Correctness component to the visible suite.
 *
 * The seed set currently has no hidden tests. Until it does, Correctness is
 * worth 50 points for passing the public suite and PRD FR8's guarantee that "a
 * fast broken submission must not outscore a slow correct one" does not hold.
 * See docs/PLAN.md §7 — this is the challenges workstream's job.
 */

import { writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { CATEGORIES, CHALLENGES } from '../packages/shared/src/challenges/index.ts'

const HERE = dirname(fileURLToPath(import.meta.url))
const OUT = resolve(HERE, 'seed.sql')

/** Postgres dollar-quoting. The tag is chosen so it cannot appear in the payload. */
function lit(value: string): string {
  const tag = value.includes('$$') ? '$cr$' : '$$'
  return `${tag}${value}${tag}`
}

const q = (value: string) => `'${value.replace(/'/g, "''")}'`

const strArray = (values: readonly string[]) =>
  `array[${values.map(q).join(', ')}]::text[]`

const jsonb = (value: unknown) => `${lit(JSON.stringify(value))}::jsonb`

/**
 * Fallback performance budgets, in milliseconds of in-process test time.
 * Per-challenge values are better and are Hamza's to set; these keep the
 * Performance component from being meaningless in the meantime.
 */
const BUDGET_MS: Record<string, number> = {
  'ch-pagination-cursor': 15,
  'ch-group-by-logs': 120,
  'ch-order-search-injection': 15,
  'ch-stable-sort': 60,
  'ch-access-guard': 15,
  'ch-n-plus-one-orders': 80,
  'ch-idempotent-charge': 60,
}

const hasHiddenTests = (testCode: string) =>
  /hidden\s*:\s*true|@hidden_test/.test(testCode)

const lines: string[] = [
  '-- =============================================================================',
  '-- Commit Roulette — seed data',
  '--',
  '-- GENERATED by supabase/seed.mts from packages/shared/src/challenges/.',
  '-- Do not edit this file. Edit the challenge and run `pnpm seed`.',
  '-- =============================================================================',
  '',
  'begin;',
  '',
  '-- Categories drive the roulette pick (see pick_challenge in 003_functions.sql),',
  '-- so the wedge order lives in data rather than in a hardcoded array.',
  'insert into public.categories (id, label, short, blurb, accent, sort_order) values',
  CATEGORIES.map(
    (c, i) =>
      `  (${q(c.id)}, ${q(c.label)}, ${q(c.short)}, ${q(c.blurb)}, ${q(c.accent)}, ${i})` +
      (i === CATEGORIES.length - 1 ? '' : ','),
  ).join('\n'),
  ';',
  '',
]

for (const challenge of CHALLENGES) {
  const budget = BUDGET_MS[challenge.id] ?? 200
  if (!hasHiddenTests(challenge.testCode)) {
    lines.push(
      `-- WARNING ${challenge.id}: no hidden tests. The 50-point Correctness`,
      `--          component is currently satisfied by the public suite.`,
    )
  }

  lines.push(
    `insert into public.challenges (id, title, category, difficulty, language, tagline,`,
    `  description, acceptance, starter_code, test_code, public_tests, par_minutes, tags)`,
    'values (',
    `  ${q(challenge.id)},`,
    `  ${q(challenge.title)},`,
    `  ${q(challenge.category)}::public.challenge_category,`,
    `  ${q(challenge.difficulty)}::public.challenge_difficulty,`,
    `  ${q(challenge.language)}::public.challenge_language,`,
    `  ${q(challenge.tagline)},`,
    `  ${lit(challenge.description)},`,
    `  ${strArray(challenge.acceptance)},`,
    `  ${lit(challenge.starterCode)},`,
    `  ${lit(challenge.testCode)},`,
    `  ${jsonb(challenge.tests)},`,
    `  ${challenge.parMinutes},`,
    `  ${strArray(challenge.tags)}`,
    ');',
    '',
    '-- Hidden suite. No client role can read this table (see 002_rls.sql).',
    'insert into public.challenge_grading (challenge_id, test_code, budget_ms)',
    `values (${q(challenge.id)}, ${lit(challenge.testCode)}, ${budget});`,
    '',
  )
}

lines.push('commit;', '')

writeFileSync(OUT, lines.join('\n'))

const withoutHidden = CHALLENGES.filter((c) => !hasHiddenTests(c.testCode))
console.log(`wrote ${OUT}`)
console.log(`  ${CATEGORIES.length} categories, ${CHALLENGES.length} challenges`)
if (withoutHidden.length) {
  console.log(
    `  ${withoutHidden.length} without hidden tests: ${withoutHidden.map((c) => c.id).join(', ')}`,
  )
  console.log('  Correctness (50 pts) is not yet protected — see docs/PLAN.md §7')
}
